[package]
name = "ch5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "struct"
path = "src/struct.rs"

[[bin]]
name = "rectangle"
path = "src/rectangle.rs"

[dependencies]
